#!/usr/bin/env bash
# Generates both the Claude Code and GitHub Copilot variants of each agent /
# orchestrator definition from the single-source files in src/.
#
# Each src/<name>.md has three sections, introduced by marker lines:
#   <<<claude>>>     Claude-variant frontmatter, verbatim (including the --- lines)
#   <<<copilot>>>    Copilot-variant frontmatter, verbatim
#   <<<body>>>       shared body; format-specific phrases are written inline as
#                    {{claude:...}} / {{copilot:...}}  (marker text must not contain "}")
#
# Rendering rules:
#   - {{claude:X}} expands to X in the Claude output and to nothing in the Copilot
#     output (and vice versa).
#   - A non-empty source line that renders to an empty string (it held only
#     markers for the other format) is dropped entirely.
#   - An AUTO-GENERATED notice is inserted between the frontmatter and the body.
#
# tools/generate.ps1 is the same generator for PowerShell; keep the two behaviorally identical.
#
# Usage:
#   ./tools/generate.sh            # (re)write the generated files
#   ./tools/generate.sh --check    # verify generated files are up to date (exit 1 if stale)

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

check=0
if [[ "${1:-}" == "--check" ]]; then
  check=1
elif [[ $# -gt 0 ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

pairs=(
  "dev-pipeline|commands/dev-pipeline.md|copilot/agents/dev-pipeline.agent.md"
  "requirements-analyst|agents/requirements-analyst.md|copilot/agents/requirements-analyst.agent.md"
  "software-architect|agents/software-architect.md|copilot/agents/software-architect.agent.md"
  "implementer|agents/implementer.md|copilot/agents/implementer.agent.md"
  "test-engineer|agents/test-engineer.md|copilot/agents/test-engineer.agent.md"
  "code-reviewer|agents/code-reviewer.md|copilot/agents/code-reviewer.agent.md"
  "pr-publisher|agents/pr-publisher.md|copilot/agents/pr-publisher.agent.md"
)

rendered=""
render_line() { # $1=line $2=keep-format $3=drop-format
  local line=$1 keep=$2 drop=$3 out prefix rest content
  out=$line
  while [[ $out == *"{{${keep}:"* ]]; do
    prefix=${out%%"{{${keep}:"*}
    rest=${out#*"{{${keep}:"}
    content=${rest%%\}\}*}
    rest=${rest#*\}\}}
    out="$prefix$content$rest"
  done
  while [[ $out == *"{{${drop}:"* ]]; do
    prefix=${out%%"{{${drop}:"*}
    rest=${out#*"{{${drop}:"}
    rest=${rest#*\}\}}
    out="$prefix$rest"
  done
  if [[ $out == *"{{"* || $out == *"}}"* ]]; then
    echo "unrendered marker remains in line: $out" >&2
    exit 1
  fi
  rendered=$out
}

build_output() { # $1=src-name $2=format ; result in $built
  local name=$1 fmt=$2 other src line cur=""
  src="src/$name.md"
  if [[ ! -f $src ]]; then
    echo "missing source file: $src" >&2
    exit 1
  fi
  for m in '<<<claude>>>' '<<<copilot>>>' '<<<body>>>'; do
    grep -qxF "$m" "$src" || { echo "$src: missing $m section" >&2; exit 1; }
  done
  if [[ $fmt == claude ]]; then other=copilot; else other=claude; fi
  built=""
  while IFS= read -r line || [[ -n $line ]]; do
    line=${line%$'\r'}
    case $line in
      '<<<claude>>>')  cur=claude;  continue ;;
      '<<<copilot>>>') cur=copilot; continue ;;
      '<<<body>>>')
        cur=body
        built+="<!-- AUTO-GENERATED from src/$name.md - edit that file and run tools/generate.ps1 (or tools/generate.sh); do not edit this file directly. -->"$'\n'
        continue ;;
    esac
    if [[ $cur == "$fmt" ]]; then
      built+="$line"$'\n'
    elif [[ $cur == body ]]; then
      if [[ $line == *"{{"* ]]; then
        render_line "$line" "$fmt" "$other"
        if [[ -n $line && -z $rendered ]]; then continue; fi
        built+="$rendered"$'\n'
      else
        built+="$line"$'\n'
      fi
    fi
  done < "$src"
}

stale=()
for pair in "${pairs[@]}"; do
  IFS='|' read -r name claude_out copilot_out <<< "$pair"
  for fmt in claude copilot; do
    if [[ $fmt == claude ]]; then out_path=$claude_out; else out_path=$copilot_out; fi
    build_output "$name" "$fmt"
    if [[ $check == 1 ]]; then
      if [[ -f $out_path ]] && cmp -s <(printf '%s' "$built") <(tr -d '\r' < "$out_path"); then
        echo "ok: $out_path"
      else
        stale+=("$out_path")
      fi
    else
      printf '%s' "$built" > "$out_path"
      echo "generated: $out_path"
    fi
  done
done

if [[ $check == 1 ]]; then
  if [[ ${#stale[@]} -gt 0 ]]; then
    echo ""
    echo "STALE: the following generated files do not match src/. Regenerate with ./tools/generate.sh (or ./tools/generate.ps1) and commit the result - never edit generated files directly:"
    for f in "${stale[@]}"; do echo "  $f"; done
    exit 1
  fi
  echo "all generated files up to date"
fi
